export const GAME_CONFIG = {
  FIXED_STEP_S: 1 / 60,
  MAX_STEPS_PER_FRAME: 5,
  MAX_PIXEL_RATIO: 2,
  CAMERA_FOV_DEG: 75,
  CAMERA_NEAR_M: 0.05,
  CAMERA_FAR_M: 120,
  PLAYER_EYE_HEIGHT_M: 1.65,
} as const;
