export const PLAYER_CONFIG = {
  PLAYER_WALK_SPEED_MPS: 3.2,
  PLAYER_RADIUS_M: 0.35,
  LOOK_SENSITIVITY_RAD_PER_PX: 0.0035,
  LOOK_PITCH_MAX_RAD: 1.4,
  STICK_MAX_TRAVEL_PX: 50,
  PLAYER_HITS_TO_DIE: 3,
  PLAYER_REGEN_DELAY_S: 4,
} as const;
