export const POINTS_CONFIG = {
  START_POINTS: 500,
  POINTS_HIT: 10,
  POINTS_KILL: 60,
  POINTS_HEADSHOT_KILL: 100,
  POINTS_KNIFE_KILL: 130,
  POINTS_REPAIR_PLANK: 10,
  REPAIR_CAP_PER_ROUND_POINTS: 500,
} as const;
