export const ROUND_CONFIG = {
  ROUND_BASE_HP: 150,
  ROUND_HP_STEP: 100,
  ROUND_HP_LINEAR_UNTIL: 9,
  ROUND_HP_GROWTH: 1.1,
  ROUND_RUN_FROM: 4,
  ROUND_BREAK_S: 10,
  ROUND_BASE_COUNT: 6,
  ROUND_COUNT_STEP: 3,
  ROUND_SPAWN_INTERVAL_S: 0.8,
} as const;
